theme: jekyll-theme-slate
title: Welcome to the NoahJele's homepage!
description: Feel free to bookmark this to keep an eye on my project updates. 

Code Review Link: https://drive.google.com/file/d/1yihZfxfzc54gEdANW6HIazwZQrH6nrMh/view?usp=sharing
 
